before_script:
    - git clone -q --depth 1 https://gitlab.com/voxl-public/utilities/ci-tools

include:
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/voxl-emulator.yml'


variables:
    GIT_SUBMODULE_STRATEGY: recursive
  
stages:
    - build_voxl_emulator_dev
    - nightly_voxl_emulator_dev
    - deploy_voxl_emulator_dev
    - build_voxl_emulator_stable
    - nightly_voxl_emulator_stable
    - deploy_voxl_emulator_stable