before_script:
    - git clone -q --depth 1 https://gitlab.com/voxl-public/utilities/ci-tools

include:
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/voxl-emulator.yml'


variables:
    GIT_SUBMODULE_STRATEGY: recursive
  
stages:

  before_script:
      - git clone -q --depth 1 https://gitlab.com/voxl-public/voxl-sdk/ci-tools

  include:
    - project: 'voxl-public/voxl-sdk/ci-tools'
      file: '/pipeline-configs/apq8096-emulator.yml'

  variables:
      GIT_SUBMODULE_STRATEGY: recursive

  stages:
      - build_apq8096_emulator_dev
      - nightly_apq8096_emulator_dev
      - deploy_apq8096_emulator_dev
      - build_apq8096_emulator_stable
      - nightly_apq8096_emulator_stable
      - deploy_apq8096_emulator_stable
